---
- name: Configure Application Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites
      apt:
        name:
          - curl
          - jq
          - git
        state: present

    - name: Install nvm (Node Version Manager) for azureuser
      become_user: azureuser
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Install Node.js v22.17.0 using nvm
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 22.17.0
        nvm use 22.17.0
        nvm alias default 22.17.0
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Install pm2 globally with npm from nvm
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install -g pm2
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Ensure app directory exists
      file:
        path: /home/azureuser/app
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Check if .env exists
      become_user: azureuser
      stat:
        path: /home/azureuser/app/backend/.env
      register: env_file

    - name: Backup existing .env file
      become_user: azureuser
      command: >
        mv /home/azureuser/app/backend/.env /tmp/app_backend.env
      when: env_file.stat.exists
      args:
        removes: /home/azureuser/app/backend/.env
        creates: /tmp/app_backend.env

    - name: Clean app directory (preserve .env)
      become_user: azureuser
      shell: |
        # Remove everything except backend directory (where .env is stored)
        find /home/azureuser/app -mindepth 1 -maxdepth 1 -not -name backend -print0 | xargs -0 rm -rf
        # Clean backend directory except .env
        if [ -d "/home/azureuser/app/backend" ]; then
          find /home/azureuser/app/backend -mindepth 1 -maxdepth 1 -not -name .env -print0 | xargs -0 rm -rf
        fi
      args:
        executable: /bin/bash

    - name: Clone or update application repository
      git:
        repo: 'https://github.com/sanjeebnepal/REACT-EXPRESS-GITHUBACTIONS-AZURE.git'
        dest: /home/azureuser/app
        version: main
        force: yes
        update: yes
      become_user: azureuser

    - name: Restore .env file if it existed
      become_user: azureuser
      command: >
        mv /tmp/app_backend.env /home/azureuser/app/backend/.env
      when: env_file.stat.exists
      args:
        removes: /tmp/app_backend.env
        creates: /home/azureuser/app/backend/.env

    - name: Create default .env if missing
      become_user: azureuser
      copy:
        dest: /home/azureuser/app/backend/.env
        content: |
          DB_HOST={{ DB_HOST }}
          DB_USER={{ DB_USER }}
          DB_PASS={{ DB_PASS }}
          DB_PORT={{ DB_PORT }}
          DB_NAME={{ DB_NAME }}
          NODE_ENV=production
          PORT=5000
      when: not env_file.stat.exists

    - name: Verify repository was cloned
      stat:
        path: /home/azureuser/app/package.json
      register: repo_check
      failed_when: not repo_check.stat.exists

    - name: Install application dependencies
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install
      args:
        chdir: /home/azureuser/app
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Restart backend if running
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 restart backend || true
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Start backend if not running
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 jlist | jq -r .[].name | grep -q '^backend$' || pm2 start /home/azureuser/app/backend/server.js --name backend
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Restart frontend if running
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 restart frontend || true
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Start frontend if not running
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 jlist | jq -r .[].name | grep -q '^frontend$' || pm2 start npm --name frontend -- start --prefix /home/azureuser/app/frontend
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Setup pm2 to start on boot
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 startup systemd -u azureuser --hp /home/azureuser
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Save pm2 process list
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 save
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser