- name: Configure Application Server
  hosts: all
  become: yes
  vars:
    db_host: "{{ db_host }}"
    db_user: "{{ db_user }}"
    db_pass: "{{ db_pass }}"
    db_port: "{{ db_port }}"
    db_name: "{{ db_name }}"

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites
      apt:
        name:
          - curl
          - jq
          - git
        state: present

    - name: Install nvm (Node Version Manager) for azureuser
      become_user: azureuser
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Install Node.js v22.17.0 using nvm
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 22.17.0
        nvm use 22.17.0
        nvm alias default 22.17.0
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Install pm2 globally with npm from nvm
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install -g pm2
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Reset application repository
      become_user: azureuser
      shell: |
        if [ -d "/home/azureuser/app/.git" ]; then
          cd /home/azureuser/app
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
        else
          git clone https://github.com/sanjeebnepal/REACT-EXPRESS-GITHUBACTIONS-AZURE.git /home/azureuser/app
        fi
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Create .env file with database configuration
      become_user: azureuser
      copy:
        dest: /home/azureuser/app/backend/.env
        content: |
          DB_HOST={{ db_host }}
          DB_USER={{ db_user }}
          DB_PASS={{ db_pass }}
          DB_PORT={{ db_port }}
          DB_NAME={{ db_name }}
          NODE_ENV=production
          PORT=4000
        mode: '0600'

    - name: Install backend dependencies
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/azureuser/app/backend && npm install
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Install frontend dependencies
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/azureuser/app/frontend && npm install
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Restart backend service
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/azureuser/app/backend
        pm2 delete backend 2>/dev/null || true
        pm2 start server.js --name backend
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Restart frontend service
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/azureuser/app/frontend
        pm2 delete frontend 2>/dev/null || true
        pm2 start "npm start" --name frontend
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser

    - name: Setup pm2 to start on boot
      shell: |
        export NVM_DIR="/home/azureuser/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        env PATH=$PATH:/home/azureuser/.nvm/versions/node/v22.17.0/bin pm2 startup systemd -u azureuser --hp /home/azureuser
      args:
        executable: /bin/bash
      become: yes
      environment:
        HOME: /root

    - name: Save pm2 process list
      become_user: azureuser
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        pm2 save
      args:
        executable: /bin/bash
      environment:
        HOME: /home/azureuser
